### PR TITLE
ML workshop

### PR DESCRIPTION
**Pull request by maciejkula**
I'll keep pushing to this PR as I add to the tutorial.

### CODE REVIEW

**Comment by maciejkula** [comment]
It's been suggested that I add a compilable Rust package at every major step of the tutorial, I'll do that next.

**Comment by erickt** [comment]
@maciejkula: this is great! would you like me to merge this in, or would you want to keep iterating on this PR?

**Comment by maciejkula** [comment]
I'll keep working on it, I'll ping you when I think it's done?

**Comment by maciejkula** [comment]
Hey @erickt I think this is in a decent state for a first attempt, happy for you to merge it!

**Comment by erickt** [comment]
Thanks so @maciejkula! We'll be happy to take anything else you think up!

**Pull request merged**
