### PR TITLE
Mondrian pattern generator instructions.

### PR DESCRIPTION
**Pull request by broesamle**
Happy to take criticism and make (last minute) changes!

### CODE REVIEW

**Comment by aepsil0n** [comment]
I don't have merge rights actually, so can't merge :/

**Comment by skade** [comment]
Please check your inbox, I got you nerd rights.

**Comment by aepsil0n** [comment]
Awesome, thank you @skade :)

**Comment by Realtin** [comment]
@skade nerd rights :D

**Pull request merged**
